### ISSUE TITLE
feat: Add individual transform properties

### ISSUE THREAD

**Issue by ScorpAL** [kutsan/stylelint-config-clean-order#15]
Add individual transform properties.

Transform elements with the `translate`, `rotate`, and `scale` properties.

```css
.target {
  translate: 50% 0;
  rotate: 30deg;
  scale: 1.2;
}
```
https://web.dev/css-individual-transform-properties/
https://chromestatus.com/feature/5705698193178624
