### ISSUE TITLE
At rules should be after declarations

### ISSUE THREAD

**Issue by tkvjs** [kutsan/stylelint-config-clean-order#21]
At rules should be after declarations because they can contain declarations like "include"

**Comment by nhantincorp** [comment]
Yes, I have some mixin to help responsive media query and i want override declarations with include at-rule.

**Comment by kutsan** [comment]
I'm sorry but in order to avoid any misunderstanding if it's possible can you provide an example code block about what is the output right now and what you want it to be look like.

**Comment by muuvmuuv** [comment]
For example this:

```scss

.slider {
  flex-basis: 100%;
  order: -1;
  border-bottom: 0.55px solid #e7e9eb;

  @include screen(md) {
    flex-basis: 0;
    order: initial;
    border-right: 0.55px solid #e7e9eb;
    border-bottom: 0;
  }
}
```

With your rule `@include` will always be before all other declarations but then the inner declarations will never take precedence over the other.
