### ISSUE TITLE
Empty Line Required before `inline-size`

### ISSUE THREAD

**Issue by rgant** [kutsan/stylelint-config-clean-order#39]
Not sure why `order/properties-order` requires an blank line before `inline-size`?

```scss
.app-loading {
  display: flex;
  align-items: center;
  justify-content: center;

  inline-size: 100vi;
  block-size: 100vb;
}
```

But without `inline-size` property this is valid:

```scss
.app-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  block-size: 100vb;
}
```

Also if I change `display: flex` to `block` it stops complaining about the empty line before `inline-size` in the original example also. So perhaps that has something to do with it?

Might not be a bug, just want to understand how it has been configured.

Stylelint version: 16.13.0
stylelint-config-clean-order version: 7.0.0

Config:

```json
{
  "extends": [
    "stylelint-config-standard-scss",
    "@stylistic/stylelint-config",
    "stylelint-config-clean-order/error"
  ],
```
