### ISSUE TITLE
[Feature request] Do not sort media-queries (?)

### ISSUE THREAD

**Issue by wouterkroes** [kutsan/stylelint-config-clean-order#6]
Hello,

**First of all thanks for this great config!**

In my project I am using [postcss-nested](https://www.npmjs.com/package/postcss-nested) and I have the following issue with the order/sorting of the media queries. I want to be able to sort/order media queries myself. 

Example below to explain why

HTML

```html
<div class="v-box v-box--pink"></div>
```

Situation 1 - current situation
De background is blue. Because media queries are order/sorted at the bottom.

CSS

```css
.v-box {
  background-color: red;
  
  &--pink {
    background-color: pink;
  }

 @media (min-width: 768px) {
    background-color: blue;
  }
}
```
Situation 2 - desired situation
De background is pink. Because I can manually place the media queries above the --pink modifier class

CSS
```css
.v-box {
  background-color: red;
  
  @media (min-width: 768px) {
    background-color: blue;
  }
  
  &--pink {
    background-color: pink;
  }
}
```

Looking forward to your response!

Greetings
